version: "3.7"
services:
  app:
    build:
      args:
        user: gbemileke
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: game-catalog
    container_name: gbemileke-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/supervisor:/etc/supervisor/conf.d/
    networks:
      - gbemileke-nt

  db:
    image: mysql:5.7
    container_name: game-catalog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - "3307:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - gbemileke-nt

  nginx:
    image: nginx:alpine
    container_name: game-catalog-nginx
    restart: unless-stopped
    ports:
      - 8100:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - gbemileke-nt

networks:
  gbemileke-nt:
    driver: bridge